version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    container_name: rssagg-data
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - rssagg-data:/var/lib/postgresql/data
volumes:
  rssagg-data:
