@endpoint = http://localhost:8080/v1

###
GET {{ endpoint }}/healthz HTTP/1.1
###

###
GET {{endpoint}}/err HTTP/1.1
###

###
POST {{endpoint}}/users HTTP/1.1
Content-Type: application/json

{
	"name": "Nick"
}
### 

###
GET {{endpoint}}/users HTTP/1.1
Authorization: ApiKey 7c4463ea98bb1bfce27add3facddc8050a697b938c075b78662a23abc12e2e14
###
